version: 1
disable_existing_loggers: false,
formatters: 
  verbose: 
    class: logging.Formatter
    format: "convert_2_file::%(asctime)s.%(msecs)03d | %(processName)s | %(levelname)s | %(module)s | %(funcName)s::%(lineno)d | %(process)d >>> %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  console:
    class : logging.StreamHandler
    formatter: verbose
    level   : INFO
    stream  : ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    backupCount: 0
    filename: ./tmp/log/
root: 
  level: INFO
  handlers:
    # - console
    - file
