version: 1
formatters: 
  standard: 
    class: logging.Formatter
    format: "convert_2_file:%(asctime)s.%(msecs)03d | %(processName)s | %(levelname)s | %(module)s | %(funcName)s:%(lineno)s | %(process)d >>> %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  console:
    class : logging.StreamHandler
    formatter: standard
    level   : INFO
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: standard
    level : DEBUG
    mode: a+
    backupCount: 20
    filename: tmp/log/log_info.log
root: 
  level: INFO
  handlers:
    - console
    # - file
